# Generated by Django 5.2.3 on 2025-06-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fix_empty_slugs'),
    ]

    operations = [
    ]
